//! Block layout algorithm.
//!
//! M2.5 scope: walk a constructed [`LayoutTree`] and assign final
//! `Dimensions` to every box. Inline / anonymous boxes are handled
//! here too in a degenerate way (1 line of text = 1 row); proper
//! inline wrapping lands in M2.6.
//!
//! Coordinate system: origin at top-left, +x right, +y down.
//! Unit: characters (M2 is text-mode rendering).

use crate::boxes::{BoxType, LayoutBox, LayoutTree};

/// Layout configuration. M2 only needs a viewport width.
#[derive(Debug, Clone, Copy)]
pub struct LayoutConfig {
    /// Available width in characters.
    pub viewport_width: f32,
}

impl Default for LayoutConfig {
    fn default() -> Self {
        Self {
            viewport_width: 80.0,
        }
    }
}

/// Run the layout pass in-place on a constructed [`LayoutTree`].
pub fn layout(tree: &mut LayoutTree, config: LayoutConfig) {
    layout_box(&mut tree.root, 0.0, 0.0, config.viewport_width);
}

/// Lay out one box at the given (x, y) within a containing width.
/// Recursive. After return, `bx.dimensions` is fully assigned.
fn layout_box(bx: &mut LayoutBox, x: f32, y: f32, containing_width: f32) {
    bx.dimensions.x = x;
    bx.dimensions.y = y;
    bx.dimensions.width = containing_width;

    match bx.box_type {
        BoxType::Block => layout_block_children(bx, containing_width),
        BoxType::Anonymous => layout_anonymous_children(bx, containing_width),
        BoxType::Inline => layout_inline_self(bx),
    }
}

fn layout_block_children(bx: &mut LayoutBox, containing_width: f32) {
    let base_x = bx.dimensions.x;
    let mut cursor_y = bx.dimensions.y;
    for child in &mut bx.children {
        // Block-formatting context: every direct child is laid out
        // at the current cursor and occupies the full container width.
        layout_box(child, base_x, cursor_y, containing_width);
        cursor_y = child.dimensions.bottom();
    }
    // The box's own height grows to exactly fit its children.
    bx.dimensions.height = (cursor_y - bx.dimensions.y).max(0.0);
}

fn layout_anonymous_children(bx: &mut LayoutBox, containing_width: f32) {
    // Anonymous block generated by `construct.rs`: contains inline
    // material. We treat each child as one "line" for now.
    let base_x = bx.dimensions.x;
    let mut cursor_y = bx.dimensions.y;
    for child in &mut bx.children {
        layout_box(child, base_x, cursor_y, containing_width);
        cursor_y = child.dimensions.bottom();
    }
    bx.dimensions.height = (cursor_y - bx.dimensions.y).max(0.0);
}

fn layout_inline_self(bx: &mut LayoutBox) {
    // Inline box: width = text length (clamped by parent, but we
    // cannot see the parent here — caller passes containing width).
    let chars = bx.text.as_deref().map(text_chars).unwrap_or(0);
    bx.dimensions.width = chars as f32;
    bx.dimensions.height = if chars == 0 { 0.0 } else { 1.0 };
}

/// Count "display columns" for a text string. For M2 we count
/// Unicode scalar values; full-width characters (CJK) get 2 columns
/// in terminals, but we ignore that until M2.6 introduces proper
/// shaping.
fn text_chars(s: &str) -> usize {
    s.chars().count()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::boxes::{BoxType, Dimensions, LayoutBox, LayoutTree};

    fn block() -> LayoutBox {
        LayoutBox::new(BoxType::Block)
    }

    fn inline_text(s: &str) -> LayoutBox {
        LayoutBox::new(BoxType::Inline).with_text(s.into())
    }

    fn anonymous_with(children: Vec<LayoutBox>) -> LayoutBox {
        let mut a = LayoutBox::new(BoxType::Anonymous);
        a.children = children;
        a
    }

    #[test]
    fn empty_block_has_zero_height() {
        let mut tree = LayoutTree { root: block() };
        layout(&mut tree, LayoutConfig::default());
        assert_eq!(tree.root.dimensions, Dimensions::new(0.0, 0.0, 80.0, 0.0));
    }

    #[test]
    fn block_children_stack_vertically_with_monotone_y() {
        // root (block) > c1 (block, 1 anon line) + c2 (block, 1 anon line)
        let mut root = block();
        let mut c1 = block();
        c1.children.push(anonymous_with(vec![inline_text("hello")]));
        let mut c2 = block();
        c2.children.push(anonymous_with(vec![inline_text("world")]));
        root.children.push(c1);
        root.children.push(c2);
        let mut tree = LayoutTree { root };

        layout(&mut tree, LayoutConfig::default());

        // c1 at y=0, height=1 → bottom=1.
        // c2 at y=1, height=1 → bottom=2.
        let c1 = &tree.root.children[0];
        let c2 = &tree.root.children[1];
        assert_eq!(c1.dimensions.y, 0.0);
        assert_eq!(c1.dimensions.height, 1.0);
        assert_eq!(c2.dimensions.y, 1.0);
        assert_eq!(c2.dimensions.height, 1.0);
        assert!(c2.dimensions.y >= c1.dimensions.bottom());
        // Root height grows to fit both children.
        assert_eq!(tree.root.dimensions.height, 2.0);
    }

    #[test]
    fn nested_blocks_propagate_width_and_y() {
        // root > outer > inner > anon(text)
        let mut root = block();
        let mut outer = block();
        let mut inner = block();
        inner.children.push(anonymous_with(vec![inline_text("x")]));
        outer.children.push(inner);
        root.children.push(outer);
        let mut tree = LayoutTree { root };

        layout(
            &mut tree,
            LayoutConfig {
                viewport_width: 40.0,
            },
        );

        assert_eq!(tree.root.dimensions.width, 40.0);
        assert_eq!(tree.root.children[0].dimensions.width, 40.0);
        assert_eq!(tree.root.children[0].children[0].dimensions.width, 40.0);
        // Text box width = chars = 1, but it lives in an anonymous
        // wrapper whose width equals the containing block (40).
        let anon = &tree.root.children[0].children[0].children[0];
        assert_eq!(anon.dimensions.width, 40.0);
        let text_box = &anon.children[0];
        assert_eq!(text_box.dimensions.width, 1.0);
    }

    #[test]
    fn anonymous_block_with_two_inline_lines_has_height_two() {
        let mut root = block();
        // Two inline text nodes side by side → still stacked because
        // construct.rs produces one anon box per inline run.
        root.children
            .push(anonymous_with(vec![inline_text("a"), inline_text("b")]));
        let mut tree = LayoutTree { root };
        layout(&mut tree, LayoutConfig::default());
        // Each inline text is 1 char → 1 line tall; both inside the
        // same anonymous wrapper → wrapper height = 2.
        assert_eq!(tree.root.dimensions.height, 2.0);
    }

    #[test]
    fn empty_text_does_not_contribute_height() {
        let mut root = block();
        root.children.push(anonymous_with(vec![inline_text("")]));
        let mut tree = LayoutTree { root };
        layout(&mut tree, LayoutConfig::default());
        assert_eq!(tree.root.dimensions.height, 0.0);
    }

    #[test]
    fn viewport_width_appears_in_root() {
        let mut tree = LayoutTree { root: block() };
        layout(
            &mut tree,
            LayoutConfig {
                viewport_width: 120.0,
            },
        );
        assert_eq!(tree.root.dimensions.width, 120.0);
    }
}
