//! Block layout algorithm.
//!
//! M2.5+M2.9 scope: walk a constructed [`LayoutTree`] and assign final
//! `Dimensions` to every box. Anonymous boxes containing inline
//! material delegate to [`crate::inline::layout_inline_run`]; when
//! an anonymous box mixes inline + block children, consecutive inline
//! runs are flushed before each block.

use crate::boxes::{BoxType, LayoutBox, LayoutTree};
use crate::inline::layout_inline_run;

/// Layout configuration. M2 only needs a viewport width.
#[derive(Debug, Clone, Copy)]
pub struct LayoutConfig {
    /// Available width in characters.
    pub viewport_width: f32,
}

impl Default for LayoutConfig {
    fn default() -> Self {
        Self {
            viewport_width: 80.0,
        }
    }
}

/// Run the layout pass in-place on a constructed [`LayoutTree`].
pub fn layout(tree: &mut LayoutTree, config: LayoutConfig) {
    layout_box(&mut tree.root, 0.0, 0.0, config.viewport_width);
}

fn layout_box(bx: &mut LayoutBox, x: f32, y: f32, containing_width: f32) {
    bx.dimensions.x = x;
    bx.dimensions.y = y;
    bx.dimensions.width = containing_width;

    match bx.box_type {
        BoxType::Block => layout_block_children(bx, containing_width),
        BoxType::Anonymous => layout_anonymous_children(bx, containing_width),
        BoxType::Inline => layout_inline_self(bx, containing_width),
    }
}

fn layout_block_children(bx: &mut LayoutBox, containing_width: f32) {
    let base_x = bx.dimensions.x;
    let mut cursor_y = bx.dimensions.y;
    for child in &mut bx.children {
        layout_box(child, base_x, cursor_y, containing_width);
        cursor_y = child.dimensions.bottom();
        // M6.0c: paragraph-like blocks get a trailing blank line so
        // successive paragraphs / headings / list items don't visually
        // merge. Real browsers do this via CSS margin-top / margin-bottom;
        // we hardcode the heuristic here until our CSS engine supports
        // margins (post-M6). The constants are tag-based to match
        // common user-agent stylesheets.
        let margin_bottom = if let Some(id) = child.element_id {
            margin_bottom_for_element(child, id)
        } else {
            0.0
        };
        cursor_y += margin_bottom;
    }
    bx.dimensions.height = (cursor_y - bx.dimensions.y).max(0.0);
}

/// Lookup the bottom margin (in lines) for a block-level element.
///
/// This is a tag-based heuristic approximating browser default styles.
/// We need the `LayoutBox` only to walk up to the element tag, but
/// since construct.rs doesn't carry the tag through to LayoutBox,
/// we approximate by `element_id`-based heuristics — for now we
/// apply 1-line margin to *all* block children, which is a slight
/// over-estimate but visually clean. M6.1 will switch to a real
/// computed-styles lookup.
fn margin_bottom_for_element(_child: &LayoutBox, _id: browser_dom::NodeId) -> f32 {
    // Heuristic: every block child gets 1 line of bottom margin.
    // This is over-generous for <div> but correct for <p>/<h1>/<h2>/<li>,
    // which is what the M6.0c fixture exercises.
    1.0
}

fn layout_anonymous_children(bx: &mut LayoutBox, containing_width: f32) {
    // Anonymous block generated by `construct.rs`. Children may be:
    //   (a) only inline content → one big inline run
    //   (b) only block content → stack as blocks
    //   (c) mixed → flush inline runs around block children
    let base_x = bx.dimensions.x;
    let base_y = bx.dimensions.y;

    // Partition indices: split children into runs separated by blocks.
    // We use indices because we need mutable access to slices.
    let n = bx.children.len();
    if n == 0 {
        bx.dimensions.height = 0.0;
        return;
    }

    let mut cursor_y = base_y;
    let mut inline_start: Option<usize> = None;
    let mut i = 0;
    while i < n {
        let is_block = bx.children[i].box_type == BoxType::Block;
        if is_block {
            // Flush pending inline run.
            if let Some(start) = inline_start.take() {
                let slice = &mut bx.children[start..i];
                let h = layout_inline_run(slice, base_x, cursor_y, containing_width);
                cursor_y += h;
            }
            layout_box(&mut bx.children[i], base_x, cursor_y, containing_width);
            cursor_y = bx.children[i].dimensions.bottom();
            // M6.0c: same 1-line paragraph margin as in layout_block_children.
            cursor_y += 1.0;
        } else if inline_start.is_none() {
            inline_start = Some(i);
        }
        i += 1;
    }
    if let Some(start) = inline_start.take() {
        let slice = &mut bx.children[start..n];
        let h = layout_inline_run(slice, base_x, cursor_y, containing_width);
        cursor_y += h;
    }

    bx.dimensions.height = (cursor_y - base_y).max(0.0);
}

fn layout_inline_self(bx: &mut LayoutBox, containing_width: f32) {
    let base_x = bx.dimensions.x;
    let base_y = bx.dimensions.y;
    if bx.children.is_empty() {
        let chars = bx.text.as_deref().map(text_chars).unwrap_or(0);
        bx.dimensions.width = chars as f32;
        bx.dimensions.height = if chars == 0 { 0.0 } else { 1.0 };
        return;
    }
    // Inline wrapper with children: delegate to inline run.
    let h = layout_inline_run(&mut bx.children, base_x, base_y, containing_width);
    bx.dimensions.height = h.max(0.0);
}

fn text_chars(s: &str) -> usize {
    s.chars().count()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::boxes::{BoxType, Dimensions, LayoutBox, LayoutTree};

    fn block() -> LayoutBox {
        LayoutBox::new(BoxType::Block)
    }

    fn inline_text(s: &str) -> LayoutBox {
        LayoutBox::new(BoxType::Inline).with_text(s.into())
    }

    fn anonymous_with(children: Vec<LayoutBox>) -> LayoutBox {
        let mut a = LayoutBox::new(BoxType::Anonymous);
        a.children = children;
        a
    }

    #[test]
    fn empty_block_has_zero_height() {
        let mut tree = LayoutTree { root: block() };
        layout(&mut tree, LayoutConfig::default());
        assert_eq!(tree.root.dimensions, Dimensions::new(0.0, 0.0, 80.0, 0.0));
    }

    #[test]
    fn block_children_stack_vertically_with_monotone_y() {
        let mut root = block();
        let mut c1 = block();
        c1.children.push(anonymous_with(vec![inline_text("hello")]));
        let mut c2 = block();
        c2.children.push(anonymous_with(vec![inline_text("world")]));
        root.children.push(c1);
        root.children.push(c2);
        let mut tree = LayoutTree { root };

        layout(&mut tree, LayoutConfig::default());

        let c1 = &tree.root.children[0];
        let c2 = &tree.root.children[1];
        assert!(c1.dimensions.height >= 1.0);
        assert!(c2.dimensions.height >= 1.0);
        assert!(c2.dimensions.y >= c1.dimensions.bottom());
        assert!(tree.root.dimensions.height >= 2.0);
    }

    #[test]
    fn nested_blocks_propagate_width_and_y() {
        let mut root = block();
        let mut outer = block();
        let mut inner = block();
        inner.children.push(anonymous_with(vec![inline_text("x")]));
        outer.children.push(inner);
        root.children.push(outer);
        let mut tree = LayoutTree { root };

        layout(
            &mut tree,
            LayoutConfig {
                viewport_width: 40.0,
            },
        );

        assert_eq!(tree.root.dimensions.width, 40.0);
        assert_eq!(tree.root.children[0].dimensions.width, 40.0);
        assert_eq!(tree.root.children[0].children[0].dimensions.width, 40.0);
    }

    #[test]
    fn empty_text_does_not_contribute_height() {
        let mut root = block();
        root.children.push(anonymous_with(vec![inline_text("")]));
        let mut tree = LayoutTree { root };
        layout(&mut tree, LayoutConfig::default());
        assert_eq!(tree.root.dimensions.height, 0.0);
    }

    #[test]
    fn viewport_width_appears_in_root() {
        let mut tree = LayoutTree { root: block() };
        layout(
            &mut tree,
            LayoutConfig {
                viewport_width: 120.0,
            },
        );
        assert_eq!(tree.root.dimensions.width, 120.0);
    }

    #[test]
    fn anonymous_with_inline_text_has_width_and_height() {
        let mut root = block();
        root.children
            .push(anonymous_with(vec![inline_text("hello")]));
        let mut tree = LayoutTree { root };
        layout(
            &mut tree,
            LayoutConfig {
                viewport_width: 80.0,
            },
        );
        let anon = &tree.root.children[0];
        assert!(anon.dimensions.height >= 1.0);
        let text_box = &anon.children[0];
        assert_eq!(text_box.dimensions.x, 0.0);
        assert!(text_box.dimensions.width >= 5.0);
    }

    #[test]
    fn anonymous_mixed_inline_block_separates_runs() {
        // anon > [inline "a", block "b" containing inline "b-content", inline "c"]
        let mut blk = block();
        blk.children
            .push(anonymous_with(vec![inline_text("b-content")]));
        let anon = anonymous_with(vec![inline_text("a"), blk, inline_text("c")]);
        let mut root = block();
        root.children.push(anon);
        let mut tree = LayoutTree { root };
        layout(
            &mut tree,
            LayoutConfig {
                viewport_width: 80.0,
            },
        );
        let anon = &tree.root.children[0];
        // Both inline runs should be visible somewhere in the layout.
        // The "a" run is on line 0, block on line 1+, "c" run after.
        assert!(anon.dimensions.height >= 3.0);
    }
}
