//! Layout primitives: rectangles, box types, layout boxes.
//!
//! For M2 we model only what's needed for a text-mode renderer:
//! - `Dimensions`: x, y, width, height
//! - `BoxType`: Block / Inline / Anonymous
//! - `LayoutBox`: typed box with optional DOM node id and text payload
//! - `LayoutTree`: the constructed tree (owned root)

use browser_dom::NodeId;

/// Rectangular dimensions in device-independent "characters" for M2.
/// Real pixel layout lands in M5.
#[derive(Debug, Clone, Copy, Default, PartialEq)]
pub struct Dimensions {
    pub x: f32,
    pub y: f32,
    pub width: f32,
    pub height: f32,
}

impl Dimensions {
    #[must_use]
    pub fn new(x: f32, y: f32, width: f32, height: f32) -> Self {
        Self {
            x,
            y,
            width,
            height,
        }
    }

    /// Top edge.
    #[must_use]
    pub fn top(&self) -> f32 {
        self.y
    }

    /// Bottom edge = y + height.
    #[must_use]
    pub fn bottom(&self) -> f32 {
        self.y + self.height
    }

    /// Right edge = x + width.
    #[must_use]
    pub fn right(&self) -> f32 {
        self.x + self.width
    }
}

/// The CSS display role of a layout box.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BoxType {
    /// block-level: div, p, h1, body, ...
    Block,
    /// inline-level: a, span, em, text content, ...
    Inline,
    /// Anonymous block generated by the layout engine to wrap
    /// mixed inline content inside a block.
    Anonymous,
}

/// A single layout box. Owns its children recursively.
#[derive(Debug, Clone)]
pub struct LayoutBox {
    pub box_type: BoxType,
    pub dimensions: Dimensions,
    /// The DOM NodeId this box corresponds to. `None` for Anonymous
    /// boxes that have no DOM counterpart.
    pub element_id: Option<NodeId>,
    /// Text content if this is a text-bearing inline box.
    pub text: Option<String>,
    /// Laid-out words from the inline word-wrap pass. Each tuple is
    /// `(word, x_in_cells, y_in_lines)`. Empty for non-text boxes and
    /// for text boxes whose `text` was all whitespace. The renderer
    /// uses this when present (it's more accurate than `text`+`x/y`
    /// because it knows where each wrapped word actually starts).
    pub words: Vec<(String, f32, f32)>,
    pub children: Vec<LayoutBox>,
}

impl LayoutBox {
    #[must_use]
    pub fn new(box_type: BoxType) -> Self {
        Self {
            box_type,
            dimensions: Dimensions::default(),
            element_id: None,
            text: None,
            words: Vec::new(),
            children: Vec::new(),
        }
    }

    #[must_use]
    pub fn with_element(mut self, id: NodeId) -> Self {
        self.element_id = Some(id);
        self
    }

    #[must_use]
    pub fn with_text(mut self, text: String) -> Self {
        self.text = Some(text);
        self
    }
}

/// The constructed layout tree.
#[derive(Debug, Clone)]
pub struct LayoutTree {
    pub root: LayoutBox,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dimensions_bottom_and_right() {
        let d = Dimensions::new(10.0, 20.0, 30.0, 40.0);
        assert_eq!(d.right(), 40.0);
        assert_eq!(d.bottom(), 60.0);
    }

    #[test]
    fn layout_box_builders() {
        let b = LayoutBox::new(BoxType::Block)
            .with_element(7)
            .with_text("hi".into());
        assert_eq!(b.element_id, Some(7));
        assert_eq!(b.text.as_deref(), Some("hi"));
    }
}
