//! Layout primitives: rectangles, box types, layout boxes.
//!
//! For M2 we model only what's needed for a text-mode renderer:
//! - `Dimensions`: x, y, width, height
//! - `BoxType`: Block / Inline / Anonymous
//! - `LayoutBox`: typed box with optional DOM node id and text payload
//! - `LayoutTree`: the constructed tree (owned root)

use browser_css_engine::BoxEdges;
use browser_dom::NodeId;

/// Rectangular dimensions in device-independent "characters" for M2.
/// Real pixel layout lands in M5.
#[derive(Debug, Clone, Copy, Default, PartialEq)]
pub struct Dimensions {
    pub x: f32,
    pub y: f32,
    pub width: f32,
    pub height: f32,
}

impl Dimensions {
    #[must_use]
    pub fn new(x: f32, y: f32, width: f32, height: f32) -> Self {
        Self {
            x,
            y,
            width,
            height,
        }
    }

    /// Top edge.
    #[must_use]
    pub fn top(&self) -> f32 {
        self.y
    }

    /// Bottom edge = y + height.
    #[must_use]
    pub fn bottom(&self) -> f32 {
        self.y + self.height
    }

    /// Right edge = x + width.
    #[must_use]
    pub fn right(&self) -> f32 {
        self.x + self.width
    }
}

/// The CSS display role of a layout box.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BoxType {
    /// block-level: div, p, h1, body, ...
    Block,
    /// inline-level: a, span, em, text content, ...
    Inline,
    /// Anonymous block generated by the layout engine to wrap
    /// mixed inline content inside a block.
    Anonymous,
    /// M32: `display: flex` — establishes a flex formatting context.
    /// Children are laid out as flex items (horizontal row or
    /// vertical column) instead of normal block/inline flow.
    Flex,
    /// M33: `display: grid` — establishes a grid formatting context.
    /// Children are placed into a 2D cell grid defined by
    /// `grid-template-columns`.
    Grid,
}

/// M32: flex-direction property. `row` (default) lays items
/// horizontally; `column` stacks them vertically.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum FlexDirection {
    #[default]
    Row,
    Column,
}

/// M32: justify-content property — how flex items are distributed
/// along the main axis when there's leftover space.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum JustifyContent {
    #[default]
    FlexStart,
    Center,
    FlexEnd,
    SpaceBetween,
}

/// M35.1: flex-wrap property — whether items wrap to next line when
/// they overflow the container's main axis.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum FlexWrap {
    #[default]
    Nowrap,
    Wrap,
}

/// M35.2: align-items property — how items are aligned along the
/// cross axis (perpendicular to flex-direction).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum AlignItems {
    #[default]
    Stretch,
    FlexStart,
    Center,
    FlexEnd,
}

/// M32: flex container properties (only meaningful when
/// `box_type == BoxType::Flex`). Defaults model the CSS defaults:
/// `flex-direction:row; justify-content:flex-start; gap:0`.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct FlexProps {
    pub direction: FlexDirection,
    pub justify: JustifyContent,
    /// Gap between items in character units (0 = no gap).
    pub gap: f32,
    /// M35.1: flex-wrap (default nowrap).
    pub wrap: FlexWrap,
    /// M35.2: align-items (default stretch).
    pub align: AlignItems,
}

impl Default for FlexProps {
    fn default() -> Self {
        Self {
            direction: FlexDirection::Row,
            justify: JustifyContent::FlexStart,
            gap: 0.0,
            wrap: FlexWrap::Nowrap,
            align: AlignItems::Stretch,
        }
    }
}

/// M33: A single grid track sizing value for `grid-template-columns`.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum GridTrack {
    /// `Nfr` — proportional fraction of leftover space.
    Fr(f32),
    /// `Npx` — fixed width in characters.
    Px(f32),
    /// `auto` — use natural content width.
    Auto,
}

/// M33: grid container properties (only meaningful when
/// `box_type == BoxType::Grid`). Defaults model `grid-template-columns:none`
/// (single auto column) + `gap:0`.
#[derive(Debug, Clone, PartialEq)]
pub struct GridProps {
    /// Column track sizes. Empty = single auto column.
    pub columns: Vec<GridTrack>,
    /// Gap between rows and columns (character units).
    pub gap: f32,
}

impl Default for GridProps {
    fn default() -> Self {
        Self {
            columns: Vec::new(),
            gap: 0.0,
        }
    }
}

/// M35.3: Explicit grid item placement from `grid-column` / `grid-row`.
/// `None` = auto-placement (default). CSS line numbers are 1-based.
#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub struct GridItemPlacement {
    /// Column start line (1-based). None = auto.
    pub col_start: Option<usize>,
    /// Column span (default 1). e.g. `grid-column: span 2` → span=2.
    pub col_span: usize,
    /// Row start line (1-based). None = auto.
    pub row_start: Option<usize>,
    /// Row span (default 1).
    pub row_span: usize,
}

/// A single layout box. Owns its children recursively.
#[derive(Debug, Clone)]
pub struct LayoutBox {
    pub box_type: BoxType,
    pub dimensions: Dimensions,
    /// The DOM NodeId this box corresponds to. `None` for Anonymous
    /// boxes that have no DOM counterpart.
    pub element_id: Option<NodeId>,
    /// Text content if this is a text-bearing inline box.
    pub text: Option<String>,
    /// Laid-out words from the inline word-wrap pass. Each tuple is
    /// `(word, x_in_cells, y_in_lines)`. Empty for non-text boxes and
    /// for text boxes whose `text` was all whitespace. The renderer
    /// uses this when present (it's more accurate than `text`+`x/y`
    /// because it knows where each wrapped word actually starts).
    pub words: Vec<(String, f32, f32)>,
    /// CSS margin box-edges (M7.1.2+). Resolved to f32 by layout at
    /// the time spacing is applied. Default = all zeros.
    pub margin: BoxEdges<browser_css_engine::Length>,
    /// CSS padding box-edges (M7.1.2+). Reserved for future use
    /// (padding affects text content origin inside the box).
    pub padding: BoxEdges<browser_css_engine::Length>,
    /// M30: marks this box as a hyperlink (`<a>`). When `colored=true`,
    /// the renderer emits ANSI underline+blue for this box's text.
    /// Screenshots parse the ANSI codes to paint blue text.
    pub link: bool,
    /// M32: flex container properties (only meaningful when
    /// `box_type == BoxType::Flex`).
    pub flex: FlexProps,
    /// M32: flex item grow factor (only meaningful when the parent
    /// is a Flex box). `flex-grow:0` = use natural width.
    pub flex_grow: f32,
    /// M33: grid container properties (only meaningful when
    /// `box_type == BoxType::Grid`).
    pub grid: GridProps,
    /// M35.3: explicit grid item placement from grid-column/grid-row.
    /// None = auto-placement (default). Only meaningful when parent is Grid.
    pub grid_placement: Option<GridItemPlacement>,
    pub children: Vec<LayoutBox>,
}

impl LayoutBox {
    #[must_use]
    pub fn new(box_type: BoxType) -> Self {
        Self {
            box_type,
            dimensions: Dimensions::default(),
            element_id: None,
            text: None,
            words: Vec::new(),
            margin: BoxEdges::default(),
            padding: BoxEdges::default(),
            link: false,
            flex: FlexProps::default(),
            flex_grow: 0.0,
            grid: GridProps::default(),
            grid_placement: None,
            children: Vec::new(),
        }
    }

    #[must_use]
    pub fn with_element(mut self, id: NodeId) -> Self {
        self.element_id = Some(id);
        self
    }

    #[must_use]
    pub fn with_text(mut self, text: String) -> Self {
        self.text = Some(text);
        self
    }

    /// Set all four margin edges to the same [`browser_css_engine::Length`].
    /// Test helper + used by construct.rs when there's no rule.
    #[must_use]
    pub fn with_margin_all(mut self, v: browser_css_engine::Length) -> Self {
        self.margin = BoxEdges::all(v);
        self
    }

    /// M30: mark this box as a hyperlink (`<a>`).
    #[must_use]
    pub fn with_link(mut self) -> Self {
        self.link = true;
        self
    }
}

/// The constructed layout tree.
#[derive(Debug, Clone)]
pub struct LayoutTree {
    pub root: LayoutBox,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dimensions_bottom_and_right() {
        let d = Dimensions::new(10.0, 20.0, 30.0, 40.0);
        assert_eq!(d.right(), 40.0);
        assert_eq!(d.bottom(), 60.0);
    }

    #[test]
    fn layout_box_builders() {
        let b = LayoutBox::new(BoxType::Block)
            .with_element(7)
            .with_text("hi".into());
        assert_eq!(b.element_id, Some(7));
        assert_eq!(b.text.as_deref(), Some("hi"));
    }
}
